# Request OTP
POST http://localhost:5000/api/v1/request-otp
Content-Type: application/json

{
    "email": "notimewaste987@gmail.com"
}

###

# Verify OTP
POST http://localhost:5000/api/v1/verify-otp
Content-Type: application/json

{
    "email": "notimewaste987@gmail.com",
    "otp": "395527"
}

###

# Get My Profile
GET http://localhost:5000/api/v1/my-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVRJ0.eyJpZCI6IjZhNWY3ODc0MTBhOGU3YTYyNTIxNDE1NCIsImlhdCI6MTc4NDY0OTIzNSwiZXhwIjoxNzg1MjU0MDM1fQ.Zs2pMZE8Sim6FkHMXkJqbCaMeTynrTSR7l4Cm21RNHI

